version: "3"

services:
 fivem:
    image: ocb/fivem
    stdin_open: true
    tty: true
    depends_on:
      - mariadb 
    volumes: 
      - ./server.cfg:/srv/server.cfg 
      - ./resources:/srv/resources 
#      - ./cache:/srv/cache 
    ports: 
      - "30120:30120/tcp" 
      - "30120:30120/udp"
